name: cicd

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4

      - name: Install dependencies
        run: |
          rye sync --no-lock

      - name: Run checks
        run: |
          rye run lint
          rye run fmt
          rye run type
          rye run pytest tests/ --cov=pkgtest --cov-report=xml

  pypi-publish:
    name: publish
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4

      - name: build
        run: rye build --clean

      - name: Publish package distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
