name: cicd

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4

      - name: Install dependencies
        run: |
          rye sync --no-lock

      - name: Run checks
        run: |
          rye run lint
          rye run fmt
          rye run type
          rye run pytest tests/ --cov=pkgtest --cov-report=xml

  cd:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: eifinger/setup-rye@v4

      - name: Bump version
        run: rye version -b patch
      # - name: Use Python Semantic Release to prepare release
      #   id: release
      #   uses: python-semantic-release/python-semantic-release@v8.3.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   if: steps.release.outputs.released == 'true'
      #   with:
      #     repository-url: https://test.pypi.org/legacy/
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
