name: cicd

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: eifinger/setup-rye@v4

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          rye sync --no-lock

      - name: Run checks
        run: |
          rye run all

  cd:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
