name: cicd

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Install gcc
        run: sudo apt get update && sudo apt install build-essential

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rye
      - uses: eifinger/setup-rye@v4

      - name: Compile C-library
        run: gcc -fPIC -shared -o ./src/c/cadd.so ./src/c/cadd.c

      - name: Install Python dependencies
        run: |
          rye sync --no-lock

      - name: Run checks
        run: |
          rye run lint
          rye run fmt
          rye run type
          rye run pytest tests/ --cov=pkgtest --cov-report=xml

      - name: Build package
        run: |
          rye build --clean --wheel

      - name: Build Docker image
        run: |
          docker build -t pkgimg .
